spring:
  application:
    name: miniblog

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:myblog}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB