create table usr
(
    user_id   bigint generated by default as identity
        primary key,
    login     varchar not null,
    pwd       varchar not null,
    firstname varchar not null,
    lastname  varchar not null
);

create table post
(
    post_id     bigint generated by default as identity
        primary key,
    owner_id    bigint  not null
        constraint fk_post_user
            references usr,
    post_name   varchar not null,
    image       bytea   not null,
    text        varchar not null,
    likes_count bigint default 0
);

create table tag
(
    tag_id   bigint generated by default as identity
        primary key,
    post_id  bigint  not null
        constraint fk_post_tag
            references post
            on delete cascade,
    tag_name varchar not null,
    constraint uq_tag_post_id_tag_name
        unique (post_id, tag_name)
);

create table likes
(
    post_id bigint not null
        constraint fk_post
            references post on delete cascade,
    user_id bigint not null
        constraint fk_user
            references usr on delete cascade,
    primary key (post_id, user_id)
);

create table comment
(
    comment_id bigint generated by default as identity
        primary key,
    owner_id   bigint  not null
        constraint fk_comment_user
            references usr,
    post_id    bigint  not null
        constraint fk_comment_post
            references post,
    text       varchar not null
);