create table usr
(
    user_id   bigint generated by default as identity
        primary key,
    login     varchar not null,
    pwd       varchar not null,
    firstname varchar not null,
    lastname  varchar not null
);